export enum ACTIVITY_TYPES {
  CONTENT_UPDATED = 'content_updated',
  CONTENT_ADDED = 'content_added',
  CONTENT_DELETED = 'content_deleted',
  USER_ADDED = 'user_added',
  USER_UPDATED = 'user_updated',
  USER_LOGGED = 'user_logged',
  USER_DELETED = 'user_deleted',
  COMMENT_ADDED = 'comment_added',
  COMMENT_UPDATED = 'comment_updated',
  COMMENT_DELETED = 'comment_deleted',
  GROUP_ADDED = 'group_added',
  GROUP_UPDATED = 'group_updated',
  GROUP_DELETED = 'group_deleted',
  EMAIL_SENT = 'email_sent',
  EMAIL_VERIFIED = 'email_verified',
}