export const FIELDS = {
  TEXT: 'text',
  TEXTAREA: 'textarea',
  TAGS: 'tags',
  IMAGE: 'img',
  FILE: 'file',
  NUMBER: 'number',
  SELECT: 'select',
  JSON: 'json',
  BOOLEAN: 'boolean',
  RADIO: 'radio',
  VIDEO_URL: 'video_url',
  MARKDOWN: 'markdown',
  URL: 'url',
  TEL: 'tel',
  DATE: 'date',
  PASSWORD: 'password',
}
